# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Synth 8-3332}  -suppress 
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.cache/wt [current_project]
set_property parent.project_path C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.ip_repo [current_project]
set_property ip_output_repo c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_125M_0/design_1_rst_mig_7series_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_125M_0/design_1_rst_mig_7series_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_125M_0/design_1_rst_mig_7series_0_125M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0_1/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0_1/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/berkaythefair/Downloads/Reza/Burak/VC707/VC707/VC707BaseSystemExtended.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
